server:
  port: 8001

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.128:3306/gmall_product?characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  # dao层
mybatis-plus:
  mapper-locations: classpath:com/atguigu/gmall/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true